# Generated by Django 2.0.13 on 2020-05-07 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('google_access_token', models.TextField(blank=True, null=True)),
                ('facebook_profile_url', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=256, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='customer/profile/')),
                ('is_custom_profile_image', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
                ('type', models.CharField(blank=True, choices=[('page_admin', 'page_admin'), ('owner', 'owner'), ('member', 'member')], default='member', max_length=200, null=True)),
                ('hometown', models.CharField(blank=True, max_length=256, null=True)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
