# Generated by Django 2.0.13 on 2020-05-08 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
        ('common', '0002_memberchatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberchatroom',
            name='room',
        ),
        migrations.AddField(
            model_name='memberchatroom',
            name='room',
            field=models.ManyToManyField(max_length=100, related_name='room_member_chat_room', to='chat.Room'),
        ),
        migrations.RemoveField(
            model_name='memberchatroom',
            name='user',
        ),
        migrations.AddField(
            model_name='memberchatroom',
            name='user',
            field=models.ManyToManyField(max_length=100, related_name='user_member_chat_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
