# Generated by Django 2.0.13 on 2020-05-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200511_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('page_admin', 'page_admin'), ('owner', 'owner'), ('member', 'member')], default='user', max_length=200, null=True),
        ),
    ]
