# Generated by Django 2.0.13 on 2020-06-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_publicroom'),
        ('common', '0007_userprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberchatroom',
            name='room',
        ),
        migrations.AddField(
            model_name='memberchatroom',
            name='room',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_member_chat_room', to='chat.Room'),
        ),
    ]
