# Generated by Django 2.0.13 on 2020-06-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200603_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Away', 'Away'), ('Do not Disturb', 'Do not Disturb')], default='Online', max_length=100, null=True),
        ),
    ]
